-- Ejecutar una vez en el SQL Editor de Supabase para habilitar el menú administrable.

create table if not exists public.menu_items (
  id bigint generated by default as identity primary key,
  label text not null,
  target_type text not null check (target_type in ('category', 'section', 'page', 'external')),
  target_value text not null,
  sort_order integer not null default 0,
  published boolean not null default true
);

alter table public.menu_items enable row level security;

drop policy if exists "Menu publico visible" on public.menu_items;
create policy "Menu publico visible" on public.menu_items for select
to anon, authenticated
using (published = true or public.is_admin());

drop policy if exists "Admin gestiona menu" on public.menu_items;
create policy "Admin gestiona menu" on public.menu_items for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

insert into public.menu_items (label, target_type, target_value, sort_order)
select seed.*
from (values
  ('Novedades','section','inicio',1),
  ('Promos','section','productos',2),
  ('Dijes','category','dijes',3),
  ('Pulseras','category','pulseras',4),
  ('Combos','category','combos',5),
  ('Nosotras','section','nosotras',6)
) as seed(label, target_type, target_value, sort_order)
where not exists (select 1 from public.menu_items);

update public.menu_items
set target_type = 'section', target_value = 'inicio'
where lower(label) = 'novedades';
