-- Ejecutar este archivo una sola vez en el SQL Editor de Supabase.

create table if not exists public.admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  price numeric(12, 2) not null check (price >= 0),
  old_price numeric(12, 2) check (old_price is null or old_price >= 0),
  badge text,
  image_url text not null,
  stock integer not null default 0 check (stock >= 0),
  published boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.products
  add column if not exists gallery_urls text[] not null default '{}';

create table if not exists public.site_content (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.categories (
  id text primary key,
  name text not null,
  image_url text,
  sort_order integer not null default 0,
  published boolean not null default true
);

alter table public.categories
  add column if not exists image_url text;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'products_category_fkey'
      and conrelid = 'public.products'::regclass
  ) then
    alter table public.products
      add constraint products_category_fkey
      foreign key (category)
      references public.categories(id)
      on update cascade
      on delete restrict;
  end if;
end
$$;

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_number text not null unique,
  customer_name text not null,
  email text not null,
  phone text not null,
  document text not null,
  delivery_method text not null,
  address text,
  city text,
  postal_code text,
  payment_method text not null,
  notes text,
  subtotal numeric(12, 2) not null check (subtotal >= 0),
  discount numeric(12, 2) not null default 0 check (discount >= 0),
  total numeric(12, 2) not null check (total >= 0),
  items jsonb not null,
  status text not null default 'pending'
    check (status in ('pending', 'contacted', 'completed', 'cancelled')),
  contacted_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.admins enable row level security;
alter table public.products enable row level security;
alter table public.site_content enable row level security;
alter table public.categories enable row level security;
alter table public.orders enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.admins where user_id = (select auth.uid())
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

drop policy if exists "Admin puede ver su perfil" on public.admins;
create policy "Admin puede ver su perfil"
on public.admins for select
to authenticated
using (user_id = (select auth.uid()));

drop policy if exists "Catalogo publico visible" on public.products;
create policy "Catalogo publico visible"
on public.products for select
to anon, authenticated
using (published = true or public.is_admin());

drop policy if exists "Admin gestiona productos" on public.products;
create policy "Admin gestiona productos"
on public.products for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Textos publicos visibles" on public.site_content;
create policy "Textos publicos visibles"
on public.site_content for select
to anon, authenticated
using (true);

drop policy if exists "Admin gestiona textos" on public.site_content;
create policy "Admin gestiona textos"
on public.site_content for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Categorias publicas visibles" on public.categories;
create policy "Categorias publicas visibles" on public.categories for select
to anon, authenticated using (published = true or public.is_admin());
drop policy if exists "Admin gestiona categorias" on public.categories;
create policy "Admin gestiona categorias" on public.categories for all
to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Clientes crean pedidos" on public.orders;
create policy "Clientes crean pedidos"
on public.orders for insert
to anon, authenticated
with check (status = 'pending');

drop policy if exists "Admin ve pedidos" on public.orders;
create policy "Admin ve pedidos"
on public.orders for select
to authenticated
using (public.is_admin());

drop policy if exists "Admin actualiza pedidos" on public.orders;
create policy "Admin actualiza pedidos"
on public.orders for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

create or replace function public.decrease_stock_for_order()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  item jsonb;
  item_id bigint;
  item_quantity integer;
begin
  for item in select * from jsonb_array_elements(new.items)
  loop
    item_id := (item->>'id')::bigint;
    item_quantity := (item->>'quantity')::integer;
    if item_quantity is null or item_quantity <= 0 then
      raise exception 'Cantidad inválida para el producto %', item_id;
    end if;
    update public.products
    set stock = stock - item_quantity,
        updated_at = now()
    where id = item_id and stock >= item_quantity;
    if not found then
      raise exception 'Stock insuficiente para el producto %', item_id;
    end if;
  end loop;
  return new;
end;
$$;

drop trigger if exists decrease_stock_after_order on public.orders;
create trigger decrease_stock_after_order
before insert on public.orders
for each row execute function public.decrease_stock_for_order();

insert into public.site_content (key, value) values
  ('announcement', '3 CUOTAS SIN INTERÉS'),
  ('hero_kicker', 'NUEVA COLECCIÓN · 2026'),
  ('hero_title', 'Lo simple se vuelve único.'),
  ('hero_description', 'Accesorios creados para acompañarte todos los días y hacer especial cada momento.'),
  ('story_title', '“Creemos que los pequeños detalles tienen el poder de cambiarlo todo.”'),
  ('story_description', 'pandora.dup nació para crear accesorios que se sientan tan personales como los recuerdos que llevamos con ellos.'),
  ('hero_image', 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1600&q=88'),
  ('editorial_main_image', 'https://images.unsplash.com/photo-1611652022419-a9419f74343d?auto=format&fit=crop&w=1400&q=85'),
  ('editorial_small_image', 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1000&q=85'),
  ('category_1_image', 'https://images.unsplash.com/photo-1535632787350-4e68ef0ac584?auto=format&fit=crop&w=900&q=85'),
  ('category_2_image', 'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?auto=format&fit=crop&w=900&q=85'),
  ('category_3_image', 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=900&q=85')
on conflict (key) do nothing;

insert into public.categories (id, name, sort_order) values
  ('dijes','Dijes',1),('pulseras','Pulseras',2),('combos','Combos',3),
  ('aros','Aros',4),('collares','Collares',5),('anillos','Anillos',6)
on conflict (id) do nothing;

insert into public.products (id,name,category,price,old_price,badge,image_url,stock,published,sort_order) values
  (1,'Aros Aura','aros',28900,32000,'NUEVO','https://images.unsplash.com/photo-1635767798638-3e25273a8236?auto=format&fit=crop&w=700&q=85',10,true,1),
  (2,'Collar Selene','collares',36500,null,'MÁS VENDIDO','https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=700&q=85',10,true,2),
  (3,'Anillo Nudo','anillos',24400,null,null,'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=700&q=85',10,true,3),
  (4,'Pulsera Siena','pulseras',31900,null,'NUEVO','https://images.unsplash.com/photo-1611652022419-a9419f74343d?auto=format&fit=crop&w=700&q=85',10,true,4),
  (5,'Aros Lía','aros',22700,null,null,'https://images.unsplash.com/photo-1535632787350-4e68ef0ac584?auto=format&fit=crop&w=700&q=85',10,true,5),
  (6,'Collar Ambar','collares',39800,43000,'ÚLTIMOS','https://images.unsplash.com/photo-1599643477877-530eb83abc8e?auto=format&fit=crop&w=700&q=85',10,true,6),
  (7,'Anillo Cielo','anillos',26900,null,null,'https://images.unsplash.com/photo-1603561596112-db1d797cc1c5?auto=format&fit=crop&w=700&q=85',10,true,7),
  (8,'Pulsera Roma','pulseras',29500,null,null,'https://images.unsplash.com/photo-1573408301185-9146fe634ad0?auto=format&fit=crop&w=700&q=85',10,true,8)
on conflict (id) do nothing;
select setval(
  pg_get_serial_sequence('public.products','id'),
  greatest((select coalesce(max(id), 1) from public.products), 1),
  true
);

insert into storage.buckets (id, name, public)
values ('products', 'products', true)
on conflict (id) do update set public = true;
insert into storage.buckets (id, name, public)
values ('site', 'site', true)
on conflict (id) do update set public = true;

drop policy if exists "Fotos publicas visibles" on storage.objects;
create policy "Fotos publicas visibles"
on storage.objects for select
to public
using (bucket_id in ('products','site'));

drop policy if exists "Admin sube fotos" on storage.objects;
create policy "Admin sube fotos"
on storage.objects for insert
to authenticated
with check (bucket_id in ('products','site') and public.is_admin());

drop policy if exists "Admin actualiza fotos" on storage.objects;
create policy "Admin actualiza fotos"
on storage.objects for update
to authenticated
using (bucket_id in ('products','site') and public.is_admin())
with check (bucket_id in ('products','site') and public.is_admin());

drop policy if exists "Admin elimina fotos" on storage.objects;
create policy "Admin elimina fotos"
on storage.objects for delete
to authenticated
using (bucket_id in ('products','site') and public.is_admin());

-- Después de crear tu usuario en Authentication > Users, ejecutá:
-- insert into public.admins (user_id) values ('UUID_DE_TU_USUARIO');
