-- Ejecutar este archivo una sola vez en el SQL Editor de Supabase.

create table if not exists public.admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  price numeric(12, 2) not null check (price >= 0),
  old_price numeric(12, 2) check (old_price is null or old_price >= 0),
  badge text,
  image_url text not null,
  stock integer not null default 0 check (stock >= 0),
  published boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.products
  add column if not exists gallery_urls text[] not null default '{}';

alter table public.products
  add column if not exists product_type text not null default 'simple'
  check (product_type in ('simple', 'charm', 'base', 'composite'));

create table if not exists public.product_components (
  composite_product_id bigint not null references public.products(id) on delete cascade,
  component_product_id bigint not null references public.products(id) on delete restrict,
  quantity integer not null check (quantity > 0),
  primary key (composite_product_id, component_product_id),
  check (composite_product_id <> component_product_id)
);

create table if not exists public.site_content (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.categories (
  id text primary key,
  name text not null,
  image_url text,
  sort_order integer not null default 0,
  published boolean not null default true
);

alter table public.categories
  add column if not exists image_url text;

create table if not exists public.menu_items (
  id bigint generated by default as identity primary key,
  label text not null,
  target_type text not null check (target_type in ('category', 'section', 'page', 'external')),
  target_value text not null,
  sort_order integer not null default 0,
  published boolean not null default true
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'products_category_fkey'
      and conrelid = 'public.products'::regclass
  ) then
    alter table public.products
      add constraint products_category_fkey
      foreign key (category)
      references public.categories(id)
      on update cascade
      on delete restrict;
  end if;
end
$$;

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_number text not null unique,
  customer_name text not null,
  email text not null,
  phone text not null,
  document text not null,
  delivery_method text not null,
  address text,
  city text,
  postal_code text,
  payment_method text not null,
  notes text,
  subtotal numeric(12, 2) not null check (subtotal >= 0),
  discount numeric(12, 2) not null default 0 check (discount >= 0),
  total numeric(12, 2) not null check (total >= 0),
  items jsonb not null,
  status text not null default 'pending'
    check (status in ('pending', 'contacted', 'completed', 'cancelled')),
  contacted_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.favorites (
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, product_id)
);

alter table public.admins enable row level security;
alter table public.products enable row level security;
alter table public.product_components enable row level security;
alter table public.site_content enable row level security;
alter table public.categories enable row level security;
alter table public.menu_items enable row level security;
alter table public.orders enable row level security;
alter table public.favorites enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.admins where user_id = (select auth.uid())
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

drop policy if exists "Admin puede ver su perfil" on public.admins;
create policy "Admin puede ver su perfil"
on public.admins for select
to authenticated
using (user_id = (select auth.uid()));

drop policy if exists "Catalogo publico visible" on public.products;
create policy "Catalogo publico visible"
on public.products for select
to anon, authenticated
using (published = true or public.is_admin());

drop policy if exists "Admin gestiona productos" on public.products;
create policy "Admin gestiona productos"
on public.products for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admin gestiona componentes" on public.product_components;
create policy "Admin gestiona componentes"
on public.product_components for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Textos publicos visibles" on public.site_content;
create policy "Textos publicos visibles"
on public.site_content for select
to anon, authenticated
using (true);

drop policy if exists "Admin gestiona textos" on public.site_content;
create policy "Admin gestiona textos"
on public.site_content for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Categorias publicas visibles" on public.categories;
create policy "Categorias publicas visibles" on public.categories for select
to anon, authenticated using (published = true or public.is_admin());
drop policy if exists "Admin gestiona categorias" on public.categories;
create policy "Admin gestiona categorias" on public.categories for all
to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Menu publico visible" on public.menu_items;
create policy "Menu publico visible" on public.menu_items for select
to anon, authenticated using (published = true or public.is_admin());
drop policy if exists "Admin gestiona menu" on public.menu_items;
create policy "Admin gestiona menu" on public.menu_items for all
to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Clientes crean pedidos" on public.orders;
create policy "Clientes crean pedidos"
on public.orders for insert
to anon, authenticated
with check (status = 'pending');

drop policy if exists "Admin ve pedidos" on public.orders;
create policy "Admin ve pedidos"
on public.orders for select
to authenticated
using (public.is_admin());

drop policy if exists "Admin actualiza pedidos" on public.orders;
create policy "Admin actualiza pedidos"
on public.orders for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Usuarios ven sus favoritos" on public.favorites;
create policy "Usuarios ven sus favoritos"
on public.favorites for select
to authenticated
using (user_id = (select auth.uid()));

drop policy if exists "Usuarios agregan favoritos" on public.favorites;
create policy "Usuarios agregan favoritos"
on public.favorites for insert
to authenticated
with check (user_id = (select auth.uid()));

drop policy if exists "Usuarios eliminan favoritos" on public.favorites;
create policy "Usuarios eliminan favoritos"
on public.favorites for delete
to authenticated
using (user_id = (select auth.uid()));

create or replace function public.get_store_products()
returns table (
  id bigint,
  name text,
  category text,
  price numeric,
  old_price numeric,
  badge text,
  image_url text,
  stock integer,
  published boolean,
  sort_order integer,
  created_at timestamptz,
  updated_at timestamptz,
  gallery_urls text[],
  product_type text,
  available_stock integer
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    p.id, p.name, p.category, p.price, p.old_price, p.badge, p.image_url,
    p.stock, p.published, p.sort_order, p.created_at, p.updated_at,
    p.gallery_urls, p.product_type,
    case
      when p.product_type = 'composite' then coalesce((
        select min(floor(component.stock::numeric / recipe.quantity))::integer
        from public.product_components recipe
        join public.products component on component.id = recipe.component_product_id
        where recipe.composite_product_id = p.id
      ), 0)
      else p.stock
    end as available_stock
  from public.products p
  where p.published = true
  order by p.sort_order, p.id;
$$;

revoke all on function public.get_store_products() from public;
grant execute on function public.get_store_products() to anon, authenticated;

create or replace function public.validate_cart_stock(p_items jsonb)
returns boolean
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  item jsonb;
  item_id bigint;
  item_quantity integer;
  ordered_type text;
begin
  if jsonb_typeof(coalesce(p_items, '[]'::jsonb)) <> 'array' then return false; end if;
  for item in select * from jsonb_array_elements(coalesce(p_items, '[]'::jsonb))
  loop
    item_id := (item->>'id')::bigint;
    item_quantity := (item->>'quantity')::integer;
    select product_type into ordered_type from public.products where id = item_id and published = true;
    if ordered_type is null or item_quantity is null or item_quantity <= 0 then return false; end if;
    if ordered_type = 'composite' and not exists (
      select 1 from public.product_components where composite_product_id = item_id
    ) then return false; end if;
  end loop;
  return not exists (
    with order_items as (
      select (entry->>'id')::bigint product_id, (entry->>'quantity')::integer quantity
      from jsonb_array_elements(coalesce(p_items, '[]'::jsonb)) entry
    ), physical_requirements as (
      select ordered.id product_id, order_items.quantity
      from order_items join public.products ordered on ordered.id = order_items.product_id
      where ordered.product_type <> 'composite'
      union all
      select recipe.component_product_id, order_items.quantity * recipe.quantity
      from order_items
      join public.products ordered on ordered.id = order_items.product_id
      join public.product_components recipe on recipe.composite_product_id = ordered.id
      where ordered.product_type = 'composite'
    ), totals as (
      select product_id, sum(quantity)::integer quantity
      from physical_requirements group by product_id
    )
    select 1
    from totals
    join public.products component on component.id = totals.product_id
    where component.product_type = 'composite' or component.stock < totals.quantity
  );
end;
$$;

revoke all on function public.validate_cart_stock(jsonb) from public;
grant execute on function public.validate_cart_stock(jsonb) to anon, authenticated;

create or replace function public.replace_product_components(
  p_product_id bigint,
  p_components jsonb
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_type text;
begin
  if not public.is_admin() then
    raise exception 'No autorizado';
  end if;

  select product_type into current_type
  from public.products
  where id = p_product_id;

  if current_type is null then
    raise exception 'Producto inexistente';
  end if;
  if jsonb_typeof(coalesce(p_components, '[]'::jsonb)) <> 'array' then
    raise exception 'La composición debe ser una lista';
  end if;
  if current_type <> 'composite' and jsonb_array_length(coalesce(p_components, '[]'::jsonb)) > 0 then
    raise exception 'Solo los productos compuestos pueden tener componentes';
  end if;
  if current_type = 'composite' and jsonb_array_length(coalesce(p_components, '[]'::jsonb)) = 0 then
    raise exception 'El producto compuesto necesita al menos un componente';
  end if;
  if exists (
    select 1
    from jsonb_array_elements(coalesce(p_components, '[]'::jsonb)) item
    left join public.products component on component.id = (item->>'productId')::bigint
    where component.id is null
       or component.id = p_product_id
       or component.product_type = 'composite'
       or coalesce((item->>'quantity')::integer, 0) <= 0
  ) then
    raise exception 'La composición contiene productos o cantidades inválidas';
  end if;

  delete from public.product_components
  where composite_product_id = p_product_id;

  insert into public.product_components (composite_product_id, component_product_id, quantity)
  select p_product_id, (item->>'productId')::bigint, sum((item->>'quantity')::integer)
  from jsonb_array_elements(coalesce(p_components, '[]'::jsonb)) item
  group by (item->>'productId')::bigint;
end;
$$;

revoke all on function public.replace_product_components(bigint, jsonb) from public;
grant execute on function public.replace_product_components(bigint, jsonb) to authenticated;

create or replace function public.decrease_stock_for_order()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  item jsonb;
  item_id bigint;
  item_quantity integer;
  ordered_type text;
  requirement record;
begin
  for item in select * from jsonb_array_elements(new.items)
  loop
    item_id := (item->>'id')::bigint;
    item_quantity := (item->>'quantity')::integer;
    if item_quantity is null or item_quantity <= 0 then
      raise exception 'Cantidad inválida para el producto %', item_id;
    end if;
    select product_type into ordered_type from public.products where id = item_id and published = true;
    if ordered_type is null then
      raise exception 'Producto inexistente: %', item_id;
    end if;
    if ordered_type = 'composite' and not exists (
      select 1 from public.product_components where composite_product_id = item_id
    ) then
      raise exception 'El producto compuesto % no tiene componentes', item_id;
    end if;
  end loop;

  for requirement in
    with order_items as (
      select
        (item->>'id')::bigint as product_id,
        (item->>'quantity')::integer as quantity
      from jsonb_array_elements(new.items) item
    ),
    physical_requirements as (
      select ordered.id as product_id, order_items.quantity as quantity
      from order_items
      join public.products ordered on ordered.id = order_items.product_id
      where ordered.product_type <> 'composite'
      union all
      select recipe.component_product_id, order_items.quantity * recipe.quantity
      from order_items
      join public.products ordered on ordered.id = order_items.product_id
      join public.product_components recipe on recipe.composite_product_id = ordered.id
      where ordered.product_type = 'composite'
    )
    select product_id, sum(quantity)::integer as quantity
    from physical_requirements
    group by product_id
    order by product_id
  loop
    update public.products
    set stock = stock - requirement.quantity,
        updated_at = now()
    where id = requirement.product_id
      and product_type <> 'composite'
      and stock >= requirement.quantity;
    if not found then
      raise exception 'Stock insuficiente para el producto %', requirement.product_id;
    end if;
  end loop;
  return new;
end;
$$;

drop trigger if exists decrease_stock_after_order on public.orders;
create trigger decrease_stock_after_order
before insert on public.orders
for each row execute function public.decrease_stock_for_order();

insert into public.site_content (key, value) values
  ('announcement', E'3 CUOTAS SIN INTERÉS\nENVÍOS A TODO EL PAÍS\n10% OFF POR TRANSFERENCIA'),
  ('hero_kicker', 'LO MÁS NUEVO · 2026'),
  ('hero_title', 'Armá tu pulsera'),
  ('hero_subtitle', 'Combiná tus charms favoritos'),
  ('hero_description', 'Accesorios creados para acompañarte todos los días y hacer especial cada momento.'),
  ('story_title', '“Creemos que los pequeños detalles tienen el poder de cambiarlo todo.”'),
  ('story_description', 'pandora.dup nació para crear accesorios que se sientan tan personales como los recuerdos que llevamos con ellos.'),
  ('gift_title', 'Un detalle especial para cada ocasión'),
  ('gift_description_1', 'Nuestros accesorios son una opción especial para regalar algo lindo, personal y con significado.'),
  ('gift_description_2', 'Realizamos ventas minoristas y también preparamos pedidos para eventos especiales como cumpleaños de 15, celebraciones, souvenirs o detalles para invitados.'),
  ('gift_description_3', 'Podés elegir pulseras, charms y combinaciones personalizadas para crear un regalo único.'),
  ('promotions_config', '[]'),
  ('hero_image', 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1600&q=88'),
  ('editorial_main_image', 'https://images.unsplash.com/photo-1611652022419-a9419f74343d?auto=format&fit=crop&w=1400&q=85'),
  ('editorial_small_image', 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1000&q=85')
on conflict (key) do nothing;

insert into public.categories (id, name, sort_order) values
  ('dijes','Dijes',1),('pulseras','Pulseras',2),('combos','Combos',3),
  ('aros','Aros',4),('collares','Collares',5),('anillos','Anillos',6)
on conflict (id) do nothing;

insert into public.menu_items (label, target_type, target_value, sort_order)
select seed.*
from (values
  ('Promos','section','promos',1),
  ('Novedades','section','productos',2),
  ('Categorías','section','categorias',3),
  ('Materiales','section','materiales',4),
  ('Eventos','section','eventos',5),
  ('Contacto','section','contacto',6)
) as seed(label, target_type, target_value, sort_order)
where not exists (select 1 from public.menu_items);


insert into public.products (id,name,category,price,old_price,badge,image_url,stock,published,sort_order) values
  (1,'Aros Aura','aros',28900,32000,'NUEVO','https://images.unsplash.com/photo-1635767798638-3e25273a8236?auto=format&fit=crop&w=700&q=85',10,true,1),
  (2,'Collar Selene','collares',36500,null,'MÁS VENDIDO','https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=700&q=85',10,true,2),
  (3,'Anillo Nudo','anillos',24400,null,null,'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=700&q=85',10,true,3),
  (4,'Pulsera Siena','pulseras',31900,null,'NUEVO','https://images.unsplash.com/photo-1611652022419-a9419f74343d?auto=format&fit=crop&w=700&q=85',10,true,4),
  (5,'Aros Lía','aros',22700,null,null,'https://images.unsplash.com/photo-1535632787350-4e68ef0ac584?auto=format&fit=crop&w=700&q=85',10,true,5),
  (6,'Collar Ambar','collares',39800,43000,'ÚLTIMOS','https://images.unsplash.com/photo-1599643477877-530eb83abc8e?auto=format&fit=crop&w=700&q=85',10,true,6),
  (7,'Anillo Cielo','anillos',26900,null,null,'https://images.unsplash.com/photo-1603561596112-db1d797cc1c5?auto=format&fit=crop&w=700&q=85',10,true,7),
  (8,'Pulsera Roma','pulseras',29500,null,null,'https://images.unsplash.com/photo-1573408301185-9146fe634ad0?auto=format&fit=crop&w=700&q=85',10,true,8)
on conflict (id) do nothing;
select setval(
  pg_get_serial_sequence('public.products','id'),
  greatest((select coalesce(max(id), 1) from public.products), 1),
  true
);

insert into storage.buckets (id, name, public)
values ('products', 'products', true)
on conflict (id) do update set public = true;
insert into storage.buckets (id, name, public)
values ('site', 'site', true)
on conflict (id) do update set public = true;

drop policy if exists "Fotos publicas visibles" on storage.objects;
create policy "Fotos publicas visibles"
on storage.objects for select
to public
using (bucket_id in ('products','site'));

drop policy if exists "Admin sube fotos" on storage.objects;
create policy "Admin sube fotos"
on storage.objects for insert
to authenticated
with check (bucket_id in ('products','site') and public.is_admin());

drop policy if exists "Admin actualiza fotos" on storage.objects;
create policy "Admin actualiza fotos"
on storage.objects for update
to authenticated
using (bucket_id in ('products','site') and public.is_admin())
with check (bucket_id in ('products','site') and public.is_admin());

drop policy if exists "Admin elimina fotos" on storage.objects;
create policy "Admin elimina fotos"
on storage.objects for delete
to authenticated
using (bucket_id in ('products','site') and public.is_admin());

-- Después de crear tu usuario en Authentication > Users, ejecutá:
-- insert into public.admins (user_id) values ('UUID_DE_TU_USUARIO');
