-- Ejecutar este archivo una sola vez en el SQL Editor de Supabase.

create table if not exists public.admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  price numeric(12, 2) not null check (price >= 0),
  old_price numeric(12, 2) check (old_price is null or old_price >= 0),
  badge text,
  image_url text not null,
  stock integer not null default 0 check (stock >= 0),
  published boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.site_content (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

alter table public.admins enable row level security;
alter table public.products enable row level security;
alter table public.site_content enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.admins where user_id = (select auth.uid())
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

drop policy if exists "Admin puede ver su perfil" on public.admins;
create policy "Admin puede ver su perfil"
on public.admins for select
to authenticated
using (user_id = (select auth.uid()));

drop policy if exists "Catalogo publico visible" on public.products;
create policy "Catalogo publico visible"
on public.products for select
to anon, authenticated
using (published = true or public.is_admin());

drop policy if exists "Admin gestiona productos" on public.products;
create policy "Admin gestiona productos"
on public.products for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Textos publicos visibles" on public.site_content;
create policy "Textos publicos visibles"
on public.site_content for select
to anon, authenticated
using (true);

drop policy if exists "Admin gestiona textos" on public.site_content;
create policy "Admin gestiona textos"
on public.site_content for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

insert into public.site_content (key, value) values
  ('announcement', '3 CUOTAS SIN INTERÉS'),
  ('hero_kicker', 'NUEVA COLECCIÓN · 2026'),
  ('hero_title', 'Lo simple se vuelve único.'),
  ('hero_description', 'Accesorios creados para acompañarte todos los días y hacer especial cada momento.'),
  ('story_title', '“Creemos que los pequeños detalles tienen el poder de cambiarlo todo.”'),
  ('story_description', 'pandora.dup nació para crear accesorios que se sientan tan personales como los recuerdos que llevamos con ellos.')
on conflict (key) do nothing;

insert into storage.buckets (id, name, public)
values ('products', 'products', true)
on conflict (id) do update set public = true;

drop policy if exists "Fotos publicas visibles" on storage.objects;
create policy "Fotos publicas visibles"
on storage.objects for select
to public
using (bucket_id = 'products');

drop policy if exists "Admin sube fotos" on storage.objects;
create policy "Admin sube fotos"
on storage.objects for insert
to authenticated
with check (bucket_id = 'products' and public.is_admin());

drop policy if exists "Admin actualiza fotos" on storage.objects;
create policy "Admin actualiza fotos"
on storage.objects for update
to authenticated
using (bucket_id = 'products' and public.is_admin())
with check (bucket_id = 'products' and public.is_admin());

drop policy if exists "Admin elimina fotos" on storage.objects;
create policy "Admin elimina fotos"
on storage.objects for delete
to authenticated
using (bucket_id = 'products' and public.is_admin());

-- Después de crear tu usuario en Authentication > Users, ejecutá:
-- insert into public.admins (user_id) values ('UUID_DE_TU_USUARIO');
